prometheus:
  server:
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
  serverFiles:
    alerting_rules.yml:
      groups:
        - name: all-alerts
          rules:
            - alert: nginx DOWN
              expr: up{service="nginx-local"} == 0 or absent(up{service="nginx-local"})
              for: 10s
              labels:
                component: nginx
                severity: critical
                priority: 1
              annotations:
                summary: Nginx down. Please take action!
                action: Restart or redeploy the service.
            - alert: demo-app Service DOWN
              expr: up{service="demo-app"} == 0 or absent(up{service="demo-app"})
              for: 10s
              labels:
                component: demo-app
                severity: warning
                priority: 1
              annotations:
                summary: demo-app service down. You wanna have a look!
                action: Restart or redeploy the service.
  
  alertmanager:
    config:
      route:
        group_by: ['severity']
        group_wait: 1m
        group_interval: 1m
        repeat_interval: 12h
        receiver: 'general-support'
        routes:
          - match:
              severity: 'critical'
            group_by: ['alertname']
            group_wait: 0m
            group_interval: 10s
            repeat_interval: 1h    
            receiver: '24x7-support'
      receivers:       
      - name: 'general-support'
        msteams_configs:
        - webhook_url: 'changeit'
          send_resolved: true
      - name: '24x7-support'
        msteams_configs:
        - webhook_url: 'changeit'
          send_resolved: true
