replicaCount: 1

image:
  repository: demo-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  profiles.grafana.com/memory.scrape: "true"
  profiles.grafana.com/memory.port_name: http2
  profiles.grafana.com/memory.port: "8080"
  profiles.grafana.com/cpu.scrape: "true"
  profiles.grafana.com/cpu.port: "8080"
  profiles.grafana.com/cpu.port_name: http2
  profiles.grafana.com/goroutine.scrape: "true"
  profiles.grafana.com/goroutine.port: "8080"

podLabels: {}

service:
  type: ClusterIP
  port: 8080

serviceAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
