apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        # The regular expression highly depends on the data in Loki, you can fine multiple fields.
        - name: 'traceID'
          matcherRegex: "traceid[\": ]*(\\w+)"
          url: '$${__value.raw}'
          datasourceUid: Tempo
        - name: 'trace_id'
          matcherRegex: "trace_id"
          matcherType: "label"
          url: '$${__value.raw}'
          datasourceUid: Tempo
          "urlDisplayLabel": "Open Trace in traceview"
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    editable: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: 'loki'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        tags: []
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} | trace_id=`$${__trace.traceId}`'
      tracesToMetrics:
        datasourceUid: 'prometheus'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      tracesToProfiles:
        customQuery: false
        datasourceUid: "pyroscope"
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        tags:
          - key: "service.name"
            value: "service_name"
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    editable: false
    jsonData:
      keepCookies: [ pyroscope_git_session ]
