apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-demo.fullname" . }}
  labels:
    {{- include "monitoring-demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monitoring-demo.selectorLabels" . | nindent 4 }}
