global:
  scrape_interval: 5s

rule_files:

scrape_configs:
  - job_name: 'otel-collector'
#    honor_timestamps: true
#    honor_labels: true
    static_configs:
      - targets: ["opentelemetry-collector:8889"]
